### ISSUE TITLE
Automatic Object Serialization

### ISSUE THREAD

**Issue by TerribleDev** [TerribleDev/UriBuilder.Fluent#1]
Would be sweet if we had `WithSerializedObject()` (also, is this the best name?)

**Comment by crozone** [comment]
I'm assuming this method would take an object (for example an anonymous type), and convert it into query parameters? If that's the case, maybe `WithQueryFromObject()`?

**Comment by TerribleDev** [comment]
yeah something like that. I did give [it a go](https://github.com/TerribleDev/UriBuilder.Fluent/pull/9) a little while back, but what I wrote did not entirely work, and it was not something I would ship.

**Comment by crozone** [comment]
https://github.com/crozone/UriBuilder.Fluent/tree/Add-WithQueryFromObject

First pass, still need to add tests.

Also need to add support for  when the object has properties that are arrays + `IEnumerable`.

**Comment by crozone** [comment]
PR: https://github.com/TerribleDev/UriBuilder.Fluent/pull/16
