### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by TonyValenti** [TerribleDev/UriBuilder.Fluent#18]
Hi @TerribleDev,
I'm considering using this library in a project and I'm a little concerned because the nuget package is stale and has not been updated in quite some time.

Would you accept a PR that:
1.  Updates version numbers to be 7.0
2. Include a nuget icon and more-marketable packaging.
3. Include a ```WithParameter(this UriBuilder bld, IEnumerable<KeyValuePair<string,string>> parameters)``` overload?

**Comment by TerribleDev** [comment]
I'll accept it and more than happy to compile it

**Comment by TerribleDev** [comment]
I can also help kick the tires if you need it 😀

**Comment by TonyValenti** [comment]
@TerribleDev - Can you accept my PR and merge?

**Comment by TerribleDev** [comment]
@TonyValenti i commented on it :)
