### ISSUE TITLE
WithParameter not encoding values?

### ISSUE THREAD

**Issue by TonyValenti** [TerribleDev/UriBuilder.Fluent#23]
Hi @TerribleDev -
I'm doing some work with Sharepoint URLs and I discovered that it appears that query string paraments are not getting properly encoded.

 For example, if I have:
```
var Uri = AbsoluteUriBuilder($@"/_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)")
    .WithParameter(new[] {
        ("@v", $@"'i:0#.w|nt service\spsearch'")
    }).ToString();
```

I would expect a URL like this to get generated:
```
https://.../_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)?@v='i%3A0%23.w%7Cnt%20service%5Cspsearch'
```
but instead a bad URL gets generated due to all the special characters in the URL.

Would you accept a PR that automatically encodes the values?  If so, what is the right method to use for the encoding?

**Comment by TonyValenti** [comment]
@TerribleDev - I just opened a PR.  Can you accept and merge?

**Comment by TerribleDev** [comment]
@TonyValenti done
